### ISSUE TITLE
CellLoop bug or possible miss use 

### ISSUE THREAD

**Issue by mojtab23** [SodiumFRP/sodium-rust#41]
I wrote a test code similar to tests but it panics at `assert_memory_free()`.

```rust
    let mut sodium_ctx = SodiumCtx::new();
    let sodium_ctx = &mut sodium_ctx;

    let delta = sodium_ctx.new_stream_sink();


    let balance_cl = sodium_ctx.transaction(
        |sodium_ctx| {
            let mut a:CellLoop<u32> = sodium_ctx.new_cell_loop();

            let update = delta.snapshot2(&a, |a:&u32, b:&u32| a + b);
            a.loop_(update.hold(0u32));

            a

        }
    );

    let listener = balance_cl.listen(move |x| println!("{:?}", x));
    delta.send(&1u32);
    delta.send(&1u32);
    delta.send(&1u32);
    listener.unlisten();
    assert_memory_freed(sodium_ctx);
```
### errors
```
thread 'main' panicked at 'memory leak detected, 4 nodes are remaining', src/main.rs:53:9
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:340
   9: test_server_sodiom::assert_memory_freed
             at .\src\main.rs:53
  10: test_server_sodiom::run
             at .\src\main.rs:45
  11: test_server_sodiom::main
             at .\src\main.rs:16
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure,i32>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:297
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libpanic_unwind\lib.rs:92
  16: std::panicking::try
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:276
  17: std::panic::catch_unwind
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panic.rs:388
  18: std::rt::lang_start_internal
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:48
  19: std::rt::lang_start<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  20: main
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  22: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\test_server_sodiom.exe` (exit code: 101)

```

**Comment by clinuxrulz** [comment]
```delta``` is still in rooted by the stack. Try this:
```
    {
        let mut sodium_ctx = SodiumCtx::new();
        let sodium_ctx = &mut sodium_ctx;

        let delta = sodium_ctx.new_stream_sink();


        let balance_cl = sodium_ctx.transaction(
            |sodium_ctx| {
                let mut a:CellLoop<u32> = sodium_ctx.new_cell_loop();

                let update = delta.snapshot2(&a, |a:&u32, b:&u32| a + b);
                a.loop_(update.hold(0u32));

                a

            }
        );

        let listener = balance_cl.listen(move |x| println!("{:?}", x));
        delta.send(&1u32);
        delta.send(&1u32);
        delta.send(&1u32);
        listener.unlisten();
    }
    assert_memory_freed(sodium_ctx);
```
Notice that ```assert_memory_freed``` is outside the braces (the stack).

**Comment by clinuxrulz** [comment]
Note: things do not start with reference count zero like in the TypeScript version.

**Comment by mojtab23** [comment]
Oh OK I got this, thank's @clinuxrulz  .
